XSPACE_CONTENT_STANDARD = {
    'name': 'XSPACE_CONTENT_STANDARD',
    'description': 'This is the Xspace Standard Content Standard',
    'force-asset-square': True,
    'strictnessLevel': 'strict',
    'image_number': 4,
    'image_file_type': '.PNG',
    'image_background_type': 'White',
    'image_color_profile': 'sRGB',
    'image_compression_type': 'Ready-For-Web',
    'image_width': 2000,
    'image_height': 2000,
    'image_margin_type': '%',
    'image_margin_top': 5,
    'image_margin_left': 5,
    'image_margin_bottom': 5,
    'image_margin_right': 5,
    'threeSixtyImage_file_type': '.PNG',
    'threeSixtyImage_background_type': 'White',
    'threeSixtyImage_color_profile': 'sRGB',
    'threeSixtyImage_compression_type': 'Ready-For-Web',
    'threeSixtyImage_margin_type': '%',
    'threeSixtyImage_margin_top': 5,
    'threeSixtyImage_margin_left': 5,
    'threeSixtyImage_margin_bottom': 5,
    'threeSixtyImage_margin_right': 5,
    'threeD_file_type': '.FX',
    'threeD_compression_type': 'Ready-For-Web',
    'video_file_type': '.MOV',
    'filename_prefix': '$NONE',
    'filename_base': '$NAME',
    'filename_delimiter': '_',
    'filename_suffix': '$NONE',
    'filename_convention': '$NAME_$D_$D.$EXT',
    'verified_background_removed': True,
}
